# Generated by Django 3.2.5 on 2021-07-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkroad',
            name='walkroad_map',
            field=models.JSONField(default=dict),
        ),
    ]
