# Generated by Django 3.2.5 on 2021-07-11 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0002_alter_walkroad_walkroad_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='walkroad',
            old_name='walkroad_info',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='walkroad',
            old_name='walkroad_finish',
            new_name='finish',
        ),
        migrations.RenameField(
            model_name='walkroad',
            old_name='walkroad_map',
            new_name='path',
        ),
        migrations.RenameField(
            model_name='walkroad',
            old_name='walkroad_start',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='walkroad',
            old_name='walkroad_tmi',
            new_name='tmi',
        ),
        migrations.RemoveField(
            model_name='walkroad',
            name='username',
        ),
        migrations.RemoveField(
            model_name='walkroad',
            name='walkroad_name',
        ),
        migrations.RemoveField(
            model_name='walkroad',
            name='walkroad_picpath',
        ),
        migrations.RemoveField(
            model_name='walkroad',
            name='walkroad_time',
        ),
        migrations.AddField(
            model_name='walkroad',
            name='distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='walkroad',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='walkroad',
            name='title',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='MapImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('walkroad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.walkroad')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('walkroad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.walkroad')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('walkroad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.walkroad')),
            ],
        ),
        migrations.AddField(
            model_name='walkroad',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_walkroads', through='maps.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
