# Generated by Django 3.2.5 on 2021-07-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20210711_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapimage',
            name='walkroad',
        ),
        migrations.AddField(
            model_name='walkroad',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='walkroads', to='maps.MapImage'),
        ),
        migrations.AddField(
            model_name='walkroad',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='walkroads', to='maps.Tag'),
        ),
    ]
