# Generated by Django 3.2.5 on 2021-07-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20210711_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walkroad',
            old_name='user',
            new_name='author',
        ),
    ]
