# Generated by Django 3.2.5 on 2021-07-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_walkroad_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkroad',
            name='info',
        ),
        migrations.AddField(
            model_name='walkroad',
            name='infowindow',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='walkroad',
            name='marker',
            field=models.JSONField(default=dict),
        ),
    ]
