# Generated by Django 3.2 on 2021-07-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_name_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='feature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='introduce',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='likehour',
            field=models.TextField(blank=True),
        ),
    ]
